### ISSUE TITLE
WebSocketError using sendbird_sdk-3.1.12

### ISSUE THREAD

**Issue by asaarnak** [sendbird/sendbird-chat-sdk-flutter#43]
We kept our application open at home screen and irregularly after hours or minutes of waiting error is thrown.
We didn't logout the user so it should reconnect instead of throwing.
https://github.com/sendbird/sendbird-sdk-flutter/blob/0cca5dd795bcd278072c813f270093d230325aed/lib/sdk/internal/sendbird_sdk_internal.dart#L162-L168
![image](https://user-images.githubusercontent.com/808420/172180651-f80e69c0-5b90-4e6b-a2de-a0b0ac993df1.png)

**Comment by YouXianMing** [comment]
We also encountered the same problem, very troubled.

**Comment by YouXianMing** [comment]
<img width="973" alt="2022-07-01 11 40 40" src="https://user-images.githubusercontent.com/5523568/176819112-b2a1c210-0398-4f5d-8a74-e7344ca07ae7.png">
This is the error message logged by Sentry, all of this are reported by Sendbird.

**Comment by derekpitts** [comment]
I found this error with the following setup:
Device: Pixel 6 Android 13, Flutter 3.3.7, sendbird_sdk: ^3.0.11
Procedure:
- Create a simple single button app.
- Set phone to Airplane mode.
- Attempt to use .connect('userid')
- Send bird api throws an error that is not caught by a try catch. The only way to catch this error is to surround connect with a runZonedGuarded. The only reason my app didn't crash was because I have a runZonedGuarded around the entire app.


Looks like the SDK is not handling no internet and a websocket error is being thrown off thread?

**Comment by asaarnak** [comment]
@danieljiwonkang98 If you could take a look would be great.
This seems to be a network timeout issue during ping request.
Would be better if the Exception would contain error message that this is ping timeout.
Or if this exception retry-able would be useful too. 

Seems like this issue is because of timeout in WatchDog Timer: https://github.com/sendbird/sendbird-chat-sdk-flutter/blob/a1012c4f13ee72b6d03942ee5f4b2876f81354a4/lib/services/network/websocket_client.dart#L195
Which is started here from Ping Timer after sending Ping command: https://github.com/sendbird/sendbird-chat-sdk-flutter/blob/a1012c4f13ee72b6d03942ee5f4b2876f81354a4/lib/services/network/websocket_client.dart#L176

```
FlutterError - This ticker was canceled: Ticker()
#0      SendbirdSdkInternal._onWebSocketError (package:sendbird_sdk/sdk/internal/sendbird_sdk_internal.dart:170)
#1      WebSocketClient.onReceiveError (package:sendbird_sdk/services/network/websocket_client.dart:129)
#2      WebSocketClient._startWatchdog.<anonymous closure> (package:sendbird_sdk/services/network/websocket_client.dart:195)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**Comment by danieljiwonkang98** [comment]
Hello! Will take a look and will leave an update on this thread. Thanks!

**Comment by danieljiwonkang98** [comment]
Hello! I understand you're encountering a WebSocket error when trying to connect to Sendbird API while in Airplane mode. This error isn't being caught by the typical try-catch block, but can be effectively handled using Dart's runZonedGuarded like mentioned above. This approach catches errors occurring within the asynchronous zone it generates. Here's an elegant way to put this into effect:

```
await runZonedGuarded<Future<void>>(
  () async {
    chatUser.value = await _sendbird.connect(userId);
  },
  (Object error, StackTrace stack) {
    _isConnecting.value = false;
    print('Encountered error: $error');
  },
);
```
The code will endeavor to connect to the Sendbird API, and should an error arise, it will be captured and handled accordingly. Furthermore, as a preventive measure, I would recommend incorporating a check for an active internet connection prior to establishing a WebSocket connection.

I hope this clarifies your issue. Should you have any more queries, please feel free to ask. Thanks!

**Comment by balaji101010** [comment]
This error occurs if we use VPN too
