### ISSUE TITLE
File is not authenticated

### ISSUE THREAD

**Issue by JosephNK** [sendbird/sendbird-chat-sdk-flutter#55]
Looking at the source, it seems that can use secureUrl. but I can't use auth=$eKey because requireAuth value is always false.

How can I use requireAuth of scureUrl property as true in FileMessage?

<img width="536" alt="스크린샷 2022-12-28 오전 3 47 27" src="https://user-images.githubusercontent.com/1622085/209709622-bb370a6c-a8d5-4bfb-84ae-276b0bcc3061.png">

I am not able to set requireAuth in sendFileMessage function.

<img width="448" alt="스크린샷 2022-12-28 오전 3 44 17" src="https://user-images.githubusercontent.com/1622085/209709651-c26239ab-74f6-4f0f-9ab7-f1be42e2640b.png">

**Comment by danieljiwonkang98** [comment]
Hello @JosephNK, thank you for your comment. When sending file message as file, the sendbird server will upload the file message to sendbird server and will return you with file message with requireAuth set as `true`. Below is an example code for sending file message with requireAuth true that you can follow. Thank you and have a happy new year!
```
final mParams = FileMessageParams.withFile(imageFile);
channel.sendFileMessage(mParams, (msg,err) {
// returns message with requireAuth set as true
});
```

**Comment by JosephNK** [comment]
Hello @danieljiwonkang98 
The way you told me is the processing of completed messages.
However, when re-entering the GroupChannel, the image is not visible.
How should I solve this?

<img width="561" alt="스크린샷 2022-12-28 오전 11 07 48" src="https://user-images.githubusercontent.com/1622085/209746172-5c8fe0d9-3805-4799-8e02-44a48babb42c.png">

**Comment by danieljiwonkang98** [comment]
Hello Joseph,
I see there is an issue with requireAuth. Will release a new update with the fix by this week. Thank you.

**Comment by danieljiwonkang98** [comment]
Hello @JosephNK, fix has been made. Please use the latest version. Thanks!
