### ISSUE TITLE
Compilation error with 3.2.9

### ISSUE THREAD

**Issue by asaarnak** [sendbird/sendbird-chat-sdk-flutter#59]
![image](https://user-images.githubusercontent.com/808420/232019322-de382957-a48c-4fbc-ae79-172948d01efd.png)

**Comment by asaarnak** [comment]
@danieljiwonkang98 
Looks like codegen issue.

**Comment by danieljiwonkang98** [comment]
@asaarnak Thanks for the comment. Will leave a comment when released with fix.

**Comment by asaarnak** [comment]
Fixed in 3.2.10
