### ISSUE TITLE
Session Manager emits an error even Token was refreshed successfully

### ISSUE THREAD

**Issue by carlosdanieldrury** [sendbird/sendbird-chat-sdk-flutter#61]
https://github.com/sendbird/sendbird-chat-sdk-flutter/blob/c575828cae36e6b991446815240a35a4956e2e11/lib/managers/session_manager.dart#L234

Hi, I've been using Session Manager to control Sendbird's connection Authentication, but when we apply a session token and this token is expired, the code is refreshing the token correctly, however, this piece of code is emitting an error even thought the token was refreshed.

**Comment by danieljiwonkang98** [comment]
Hello this issue have been fixed! Closing Ticket.
