### ISSUE TITLE
Update dependency `connectivity_plus` to `^4.0.0`

### ISSUE THREAD

**Issue by asaarnak** [sendbird/sendbird-chat-sdk-flutter#62]

**Comment by asaarnak** [comment]
@danieljiwonkang98 Could you take a look. This should be ready to merge.

**Comment by danieljiwonkang98** [comment]
Hello @asaarnak, will take a look and will make the update. Thank you!

**Comment by chandrabezzo** [comment]
Hi, how long we need to waiting this PR merged?
