### ISSUE TITLE
Public Discoverable Group Channels cannot be queried if user is not joined.

### ISSUE THREAD

**Issue by JakeSeo** [sendbird/sendbird-chat-sdk-flutter#64]
Hi, I tried to query Public Group Channels and it did not work as stated in the document. So I emailed the Sendbird team and got the following answer.

In `main/model/channel/group_channel_filter.dart`, adding `@JsonKey(name: 'public_membership_mode')` to `publicMembershipFilter` would fix the problem - the key is currently `public_membership_filter` which is not correct to send public membership filter.

I downloaded the sdk, applied it locally and it actually fixed the issue. Could you please also apply this into the repository and upcoming updates on pub.dev?

**Comment by danieljiwonkang98** [comment]
Hello @JakeSeo this issue has been resolved! Closing ticket.
